# Site settings
title: Thought Refactory
email: twash@cs.odu.edu
description: > # this means to ignore newlines until "baseurl:"
  Code &
  Coffee &
  Cookies &
  Rambling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://washt.me" # the base hostname & protocol for your site
twitter_username: getbuckTuck
github_username:  washt

# Build settings
markdown: github
